name: ebookapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^5.6.5
  cupertino_icons: ^1.0.8 
  lottie: ^3.3.1
  get: ^4.7.2
  google_fonts: ^6.2.1
  firebase_core: ^3.12.1
  firebase_auth: ^5.4.2
  google_sign_in: ^6.2.2
  flutter_keyboard_visibility: ^6.0.0
  image_picker: ^1.1.2

  # Optional (if needed for local storage)
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  uuid: ^4.5.1
  # hive: ^2.2.3
  # hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/mainsplash.json
    - assets/image/loading.json
    - assets/image/logo.json
    # - assets/images/   # Add this if you store book images locally
