// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqb0DRSnhSx7xLZ5Mw0kT1goW_xouH448',
    appId: '1:579954557861:web:e81edaf989db2d592b1e4c',
    messagingSenderId: '579954557861',
    projectId: 'ebookapp-6e72b',
    authDomain: 'ebookapp-6e72b.firebaseapp.com',
    storageBucket: 'ebookapp-6e72b.firebasestorage.app',
    measurementId: 'G-TVKMD4PN1K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAtvxxVMfIgbYtJZwt8YrWdDZ7ynAZRsM',
    appId: '1:579954557861:android:637b9dba3516c1772b1e4c',
    messagingSenderId: '579954557861',
    projectId: 'ebookapp-6e72b',
    storageBucket: 'ebookapp-6e72b.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqb0DRSnhSx7xLZ5Mw0kT1goW_xouH448',
    appId: '1:579954557861:web:2198bf68816bea602b1e4c',
    messagingSenderId: '579954557861',
    projectId: 'ebookapp-6e72b',
    authDomain: 'ebookapp-6e72b.firebaseapp.com',
    storageBucket: 'ebookapp-6e72b.firebasestorage.app',
    measurementId: 'G-8PJHR1J6YJ',
  );

}